[build]
  command = "npm run build"
  dist = "dist/veysel-demirel-angular-web-app/browser"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "@angular/ssr", "serverless-http", "nodemailer"]
  node_bundler = "esbuild"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/ssr"
  status = 200
