[build]
  command = "npm run build"
  publish = "dist/veysel-demirel-angular-web-app/browser"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@angular/ssr", "@angular/compiler", "express", "serverless-http", "nodemailer"]
  node_bundler = "esbuild"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/ssr"
  status = 200
