[build]
  command = "npm run build"
  publish = "dist/veysel-demirel-angular-web-app/browser"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
